package corba1;


/**
* corba1/pruebaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prueba.idl
* sábado 25 de abril de 2020 08:46:10 PM CDT
*/

public interface pruebaOperations 
{
  String generar (String numero);
} // interface pruebaOperations
