package corba1;

/**
* corba1/pruebaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prueba.idl
* sábado 25 de abril de 2020 08:46:10 PM CDT
*/

public final class pruebaHolder implements org.omg.CORBA.portable.Streamable
{
  public corba1.prueba value = null;

  public pruebaHolder ()
  {
  }

  public pruebaHolder (corba1.prueba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba1.pruebaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba1.pruebaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba1.pruebaHelper.type ();
  }

}
