package corba1;


/**
* corba1/pruebaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from prueba.idl
* sábado 25 de abril de 2020 08:46:10 PM CDT
*/

public abstract class pruebaPOA extends org.omg.PortableServer.Servant
 implements corba1.pruebaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("generar", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba1/prueba/generar
       {
         String numero = in.read_string ();
         String $result = null;
         $result = this.generar (numero);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba1/prueba:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public prueba _this() 
  {
    return pruebaHelper.narrow(
    super._this_object());
  }

  public prueba _this(org.omg.CORBA.ORB orb) 
  {
    return pruebaHelper.narrow(
    super._this_object(orb));
  }


} // class pruebaPOA
